server:
  port: 26000
spring:
  profiles:
    active: develop
  datasource:
    url: # 数据库连接地址
    username: # 数据库连接账户
    password: # 数据库连接密码
  data:
    redis:
      host: # redis连接地址
      port: # redis连接端口
      database: # redis数据库
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
knife4j:
  enable: true
  setting:
    enable-home-custom: true
    home-custom-path: classpath:knife4j/home.md
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: Apache License 2.0 | Copyright  2023-[Moyok](https://blog.integer.top)
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    persistAuthorization: true
  group-configs:
    - group: 接口文档v1
      packages-to-scan:
        - top.integer.blog.controller
cross:
  list:
    - path: /**
      origin:
        - http://127.0.0.1:5173 # 跨域地址
        - http://127.0.0.1:5174
        - http://localhost:5173
        - http://10.205.253.83:5173
mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
file:
  bath-path: /
  mode: tencent_cloud
  polices:
    - access-key: # access-key
      secret-key: # secret-key
      endpoint: # 地域
      bucket: # 存储桶名
      domain: # 域名，末尾不要有 /
      redirect-domain: # 重定向地址
      http-protocol: # 协议 http/https
      mode: # 存储方式
